// automatically generated by the FlatBuffers compiler, do not modify

package com.zpb.fbs.user;

/**
 * 能力
 */
@SuppressWarnings("unused")
public final class Ability {
  private Ability() { }
  public static final byte NONE = 0;
  public static final byte Reading = 1;
  public static final byte Swimming = 2;
  public static final byte Running = 3;

  public static final String[] names = { "NONE", "Reading", "Swimming", "Running", };

  public static String name(int e) { return names[e]; }
}

