// automatically generated by the FlatBuffers compiler, do not modify

package com.zpb.fbs.user;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * 通用响应类型
 */
@SuppressWarnings("unused")
public final class BaseResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static BaseResponse getRootAsBaseResponse(ByteBuffer _bb) { return getRootAsBaseResponse(_bb, new BaseResponse()); }
  public static BaseResponse getRootAsBaseResponse(ByteBuffer _bb, BaseResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BaseResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * 响应码
   */
  public int code() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean mutateCode(int code) { int o = __offset(4); if (o != 0) { bb.putInt(o + bb_pos, code); return true; } else { return false; } }
  /**
   * 数据 data
   */
  public String data() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer dataAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer dataInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  /**
   * 结果描述
   */
  public String message() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer messageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createBaseResponse(FlatBufferBuilder builder,
      int code,
      int dataOffset,
      int messageOffset) {
    builder.startTable(3);
    BaseResponse.addMessage(builder, messageOffset);
    BaseResponse.addData(builder, dataOffset);
    BaseResponse.addCode(builder, code);
    return BaseResponse.endBaseResponse(builder);
  }

  public static void startBaseResponse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addCode(FlatBufferBuilder builder, int code) { builder.addInt(0, code, 0); }
  public static void addData(FlatBufferBuilder builder, int dataOffset) { builder.addOffset(1, dataOffset, 0); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(2, messageOffset, 0); }
  public static int endBaseResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BaseResponse get(int j) { return get(new BaseResponse(), j); }
    public BaseResponse get(BaseResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

