// automatically generated by the FlatBuffers compiler, do not modify

package com.zpb.fbs.user;

/**
 * 职业等级
 */
@SuppressWarnings("unused")
public final class Level {
  private Level() { }
  public static final byte JUNIOU = 1;
  public static final byte MIDDLE = 2;
  public static final byte SENIOR = 3;

  public static final String[] names = { "JUNIOU", "MIDDLE", "SENIOR", };

  public static String name(int e) { return names[e - JUNIOU]; }
}

