// automatically generated by the FlatBuffers compiler, do not modify

package com.zpb.fbs.user;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * 电话信息
 */
@SuppressWarnings("unused")
public final class Phone extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Phone __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int number() { return bb.getInt(bb_pos + 0); }
  public void mutateNumber(int number) { bb.putInt(bb_pos + 0, number); }

  public static int createPhone(FlatBufferBuilder builder, int number) {
    builder.prep(4, 4);
    builder.putInt(number);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Phone get(int j) { return get(new Phone(), j); }
    public Phone get(Phone obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

