// automatically generated by the FlatBuffers compiler, do not modify

package com.zpb.fbs.user;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * 跑步
 */
@SuppressWarnings("unused")
public final class Running extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static Running getRootAsRunning(ByteBuffer _bb) { return getRootAsRunning(_bb, new Running()); }
  public static Running getRootAsRunning(ByteBuffer _bb, Running obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Running __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String running() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer runningAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer runningInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createRunning(FlatBufferBuilder builder,
      int runningOffset) {
    builder.startTable(1);
    Running.addRunning(builder, runningOffset);
    return Running.endRunning(builder);
  }

  public static void startRunning(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addRunning(FlatBufferBuilder builder, int runningOffset) { builder.addOffset(0, runningOffset, 0); }
  public static int endRunning(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Running get(int j) { return get(new Running(), j); }
    public Running get(Running obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

