// automatically generated by the FlatBuffers compiler, do not modify

package com.zpb.fbs.user;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

/**
 * 定义对象
 */
@SuppressWarnings("unused")
public final class User extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static User getRootAsUser(ByteBuffer _bb) { return getRootAsUser(_bb, new User()); }
  public static User getRootAsUser(ByteBuffer _bb, User obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public User __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long id() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean mutateId(long id) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, id); return true; } else { return false; } }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public long age() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public boolean mutateAge(long age) { int o = __offset(8); if (o != 0) { bb.putInt(o + bb_pos, (int) age); return true; } else { return false; } }
  public double salary() { int o = __offset(10); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public boolean mutateSalary(double salary) { int o = __offset(10); if (o != 0) { bb.putDouble(o + bb_pos, salary); return true; } else { return false; } }
  public long createTime() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean mutateCreateTime(long create_time) { int o = __offset(12); if (o != 0) { bb.putLong(o + bb_pos, create_time); return true; } else { return false; } }
  public long updateTime() { int o = __offset(14); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public boolean mutateUpdateTime(long update_time) { int o = __offset(14); if (o != 0) { bb.putLong(o + bb_pos, update_time); return true; } else { return false; } }
  public byte level() { int o = __offset(16); return o != 0 ? bb.get(o + bb_pos) : 2; }
  public boolean mutateLevel(byte level) { int o = __offset(16); if (o != 0) { bb.put(o + bb_pos, level); return true; } else { return false; } }
  public com.zpb.fbs.user.Address address() { return address(new com.zpb.fbs.user.Address()); }
  public com.zpb.fbs.user.Address address(com.zpb.fbs.user.Address obj) { int o = __offset(18); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public com.zpb.fbs.user.Phone phone() { return phone(new com.zpb.fbs.user.Phone()); }
  public com.zpb.fbs.user.Phone phone(com.zpb.fbs.user.Phone obj) { int o = __offset(20); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public byte abilityType() { int o = __offset(22); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table ability(Table obj) { int o = __offset(24); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static void startUser(FlatBufferBuilder builder) { builder.startTable(11); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addLong(0, id, 0L); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addAge(FlatBufferBuilder builder, long age) { builder.addInt(2, (int) age, (int) 0L); }
  public static void addSalary(FlatBufferBuilder builder, double salary) { builder.addDouble(3, salary, 0.0); }
  public static void addCreateTime(FlatBufferBuilder builder, long createTime) { builder.addLong(4, createTime, 0L); }
  public static void addUpdateTime(FlatBufferBuilder builder, long updateTime) { builder.addLong(5, updateTime, 0L); }
  public static void addLevel(FlatBufferBuilder builder, byte level) { builder.addByte(6, level, 2); }
  public static void addAddress(FlatBufferBuilder builder, int addressOffset) { builder.addOffset(7, addressOffset, 0); }
  public static void addPhone(FlatBufferBuilder builder, int phoneOffset) { builder.addStruct(8, phoneOffset, 0); }
  public static void addAbilityType(FlatBufferBuilder builder, byte abilityType) { builder.addByte(9, abilityType, 0); }
  public static void addAbility(FlatBufferBuilder builder, int abilityOffset) { builder.addOffset(10, abilityOffset, 0); }
  public static int endUser(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishUserBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedUserBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public User get(int j) { return get(new User(), j); }
    public User get(User obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

